name: Prettier

on: [push]

jobs:
  run-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run format
        run: npm run format

      - name: Compile
        run: npm run prod

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: prettier
